### ISSUE TITLE
Dark mode styles

### ISSUE THREAD

**Issue by Dhravya** [steven-tey/chathn#1]
The colors don't look right when i have prefers-dark-mode enabled on my device

Here:
![image](https://github.com/steven-tey/chathn/assets/63950637/86a29d54-3d62-4fc5-8bf1-c840716d01b6)

Possible fix: 
1. `darkMode:"class"` in tailwind config
2. Write darkmode tailwind styles with `dark:`

**Comment by steven-tey** [comment]
whoops, good catch, thank you! just fixed it! :)
